JANELA1 = "JANELA1"
JANELA2 = "JANELA2"
JANELA3 = "JANELA3"
JANELA4 = "JANELA4"
JANELA5 = "JANELA5"
JANELA6 = "JANELA6"

INI_LABEL = "INICIALIZA"
DESA_LABEL = "DESALABEL"

false_s = "False"
true_s  = "True"

PROCESSADOR = "PROCESSADOR"
RAM_S = "RAM"
TEMPERATURA_S = "TEMPERATURA"